/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:3fb1e627-966d-4ce6-8133-172a3294acff",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_YZrUXxx7w",
    "aws_user_pools_web_client_id": "6b9i7j4ipu8dcgcm2peqe6que6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fctbvbpdefekvdv4ri2nqq7tsu.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-igjktuhlwfhwnltitjsqw2lk6i"
};


export default awsmobile;
